Supports custom Docker image
Currently just `bash` and `ash` shells are supported, and on some
distributions. I could not get a grasp on how to make `ash` behave
consistently on other images (than the ones being tested). Hopefully,
someday, `dash` will also be supported.

diff --git a/ship b/ship
--- a/ship
+++ b/ship
@@ -6,21 +6,27 @@
 #
 # Author: Augusto Pascutti <augusto.hp+oss@gmail.com>
 #
-# TODO: Parse all existing options
-# TODO: Support "ash" and "bash" history
-# TODO: Support different docker images
-# TODO: Option to force recreation of Dockerfile
 # TODO: Git ignores the `OPTION_CHOME` directory
+# TODO: Test history writting for different shells
 
-PROGRAM_NAME=$(basename $0)
+PROGRAM_NAME=$(basename "$0")
 PROGRAM_VERSION=${PROGRAM_VERSION:-"1.0.0"}
+PROGRAM_URL="https://github.com/augustohp/ship"
 
 OPTION_CHOME=".ship"
-OPTION_IMAGE="alpine:latest"
+OPTION_IMAGE=""
 OPTION_DOCKERFILE="Dockerfile"
-OPTION_CMD="sh"
+OPTION_FORCE_RECREATION=""
+OPTION_SHELL_TEST="bash ash"
 
+ENTRYPOINT="main"
+GIT=$(command -v GIT)
 DOCKER=$(command -v docker)
+
+if [ -n "$DEBUG" ] 
+then
+	set -x
+fi
 
 trap cleanup 0 1 2 3 6
 cleanup()
@@ -28,11 +34,18 @@ cleanup()
 	rm -rf "${OPTION_CHOME}"
 }
 
+# Usage: display_version
+display_version()
+{
+	echo "$PROGRAM_NAME $PROGRAM_VERSION"
+}
+
 # Usage: display_help
 display_help()
 {
 	cat <<-EOT
-	Usage: $PROGRAM_NAME [-o <filename>] [-c <command>] [-f] [image]
+	Usage: $PROGRAM_NAME [-o <filename>] [-f] <image>
+	       $PROGRAM_NAME <-d | --detect-shell> <image>
 	       $PROGRAM_NAME <-h | --help>
 	       $PROGRAM_NAME <-v | --version>
 
@@ -40,38 +53,72 @@ display_help()
 	into RUN instructions.
 
 	Arguments:
-
 	  image                    The name of Dockerimage to be executed. 
 	                           The image must have bash installed.
-	                           Default: ${OPTION_IMAGE}.
-
 	Options:
-
 	  -o | --out <filename>    The name of the Dockerfile to be creared.
 	                           Default: ${OPTION_DOCKERFILE}.
-	  -c | --command <cmd>     The shell command to execute.
-	                           Default: ${OPTION_CMD}.
 	  -f | --force             Re-creates ${OPTION_DOCKERFILE} if it
 	                           already exists.
+	  -d | --detect-shell      Outputs the shell available in the image.
+	                           Shells tested: ${OPTION_SHELL_TEST}
 	EOT
+}
+
+# Usage: detect_shell_available
+# Example: detect_shell_available
+#          ash
+detect_shell_available()
+{
+	for shellbin in ${OPTION_SHELL_TEST}
+	do
+		if inspect_image "${shellbin}"
+		then
+			echo "${shellbin}"
+			return 0
+		fi
+	done
+	return 1
 }
 
 
 # Usage: inspect_image <inspection>
-# Example: inspect_image alpine:3.10 whomai
+# Example: inspect_image whomai
 inspect_image()
 {
-	inspection="${*:1}"
+	inspection="${1}"
 
 	$DOCKER run \
 		--rm \
 		"${OPTION_IMAGE}" \
-		"${inspection}"
+		"${inspection}" 2> /dev/null
+
+	return $?
+}
+
+# Example: generate_author_info
+#          Augusto Pascutti <augusto.hp@gmail.com>
+generate_author_info()
+{
+	if [ -z "$GIT" ]
+	then
+		return 0
+	fi
+
+	name=$($GIT config user.name)
+	email=$($GIT config user.email)
+	echo "${name} <${email}>"
 }
 
 # Usage: main
 main()
 {
+	if [ -z "${OPTION_IMAGE}" ]
+	then
+		echo "No image specified! Run 'ship --help' for more information." 
+		return 1
+	fi
+
 	user=$(inspect_image 'whoami')
 	if [ "$user" = "root" ]
 	then 
@@ -81,18 +128,59 @@ main()
 	fi
 
 	container_home="${PWD}/${OPTION_CHOME}"
+	OPTION_CMD="$(detect_shell_available)"
+	case "${OPTION_CMD}" in
+		ash)
+			history_file=".ash_history"
+			;;
+		bash)
+			history_file=".bash_history"
+			;;
+		*)
+			echo "Error: This image does not have any supported shell!"
+			echo "Please, submit an issue to ${PROGRAM_URL}."
+			return 2
+			;;
+	esac
+
 	$DOCKER run \
 		--rm \
 		--name "ship-generating-dockerfile" \
 		-it \
+		-e "HISTSIZE=10000" \
+		-e 'HISTCONTROL="erasedups:ignoreboth"' \
+		-e 'HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history:clear"' \
 		-v "${container_home}:${home}" \
+		-v "${PWD}:/home/developer" \
 		"${OPTION_IMAGE}" \
 		"${OPTION_CMD}"
 	echo
-	while read line
+
+	saved_history_file="${container_home}/${history_file}"
+	if [ ! -f "${saved_history_file}" ]
+	then
+		echo "Error: history file not saved! I am terribly sorry for that."
+		echo "Please, create an issue at ${PROGRAM_URL}."
+		return 2
+	fi
+
+	if [ -n "${OPTION_FORCE_RECREATION}" ]
+	then
+		rm "${OPTION_DOCKERFILE}"
+	fi
+
+	user_info=$(generate_author_info)
+	cat <<-EOT > "${OPTION_DOCKERFILE}"
+	# Generated by ${PROGRAM_URL}
+	FROM ${OPTION_IMAGE}
+	LABEL maintainer="${user_info}"
+
+	EOT
+
+	while read -r line
 	do
 		echo "RUN ${line}" >> "${OPTION_DOCKERFILE}"
-	done < "${container_home}/.ash_history"
+	done < "${saved_history_file}"
 	echo "${OPTION_DOCKERFILE} writeen successfully!"
 }
 
@@ -104,13 +192,29 @@ do
 	fi
 
 	case "$1" in
-		-h|--help)
-			display_help
-			exit 0
+		-h|--help|help)
+			ENTRYPOINT="display_help"
+			;;
+		-v|--version|version)
+			ENTRYPOINT="display_version"
+			;;
+		-d|--detect-shell)
+			ENTRYPOINT="detect_shell_available"
+			;;
+		-f|--force)
+			OPTION_FORCE_RECREATION=1
+			;;
+		-o|--out)
+			OPTION_DOCKERFILE="$2"
+			shift
+			;;
+		*)
+			OPTION_IMAGE=$1
 			;;
 	esac
 	shift
 done
 
-main
+$ENTRYPOINT
+exit $?
 
